### PR TITLE
Update conflicts with PF2e Ability Manager

### PR DESCRIPTION
**Pull request by MrVauxs**

### CODE REVIEW

**Comment by mouse0270** [comment]
Do you still experience this issue with v2 of MM+

**Comment by mouse0270** [comment]
Yeah global conflicts had to be removed. Many people reported to me that it was causing issues and hanging up their foundry clients.

I plan on reworking global conflicts and re-adding the feature. I just have to develop a new system for doing so. I have an idea but want to make sure whatever I implement gets put in a way that it doesn't cause issues for so many people.

I will leave this open, to include this in the new system once I implement it.

**Comment by mouse0270** [comment]
included in v2.1.2

**Comment by MrVauxs** [comment]
Question, where can one find the google sheet mentioned in changelogs? It's not in the README.

**Comment by mouse0270** [comment]
[Google Sheet](https://docs.google.com/spreadsheets/d/1eRcaqt8VtgDRC-iWP3SfOnXh-7kIw2k7po9-3dcftAk/edit?usp=sharing) Its just a sheet that stores the data. Its read only. Which sucks for me cause it means I have to maintain it.

**Pull request closed without merging**
